targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
          explicit_to_json: true
      injectable_generator:
        options:
          auto_register: true
          class_name_pattern: ".*Service$|.*Repository$|.*Dao$|.*Bloc$"
