// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2vMg7mOxGqgrhgpTIkpQAyrX0BIngL2U',
    appId: '1:804709425801:web:0209301a021128af7a1c58',
    messagingSenderId: '804709425801',
    projectId: 'expensebuddy-app',
    authDomain: 'expensebuddy-app.firebaseapp.com',
    storageBucket: 'expensebuddy-app.firebasestorage.app',
    measurementId: 'G-9R0LSM7J2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDHRBMAVXZGcy7znBpoMbF8ya5d65ok3Q',
    appId: '1:804709425801:android:dae1b1f966d780657a1c58',
    messagingSenderId: '804709425801',
    projectId: 'expensebuddy-app',
    storageBucket: 'expensebuddy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgPbGi7BxS_bLWj5iPXWRWRBpmRoIdshw',
    appId: '1:804709425801:ios:f5124806ab72d8d57a1c58',
    messagingSenderId: '804709425801',
    projectId: 'expensebuddy-app',
    storageBucket: 'expensebuddy-app.firebasestorage.app',
    iosClientId: '804709425801-1ec7hoh304npcu2649bqqitpdkeg3c07.apps.googleusercontent.com',
    iosBundleId: 'com.expensebuddy',
  );
}
